AWSTemplateFormatVersion: '2010-09-09'
Description: Set up the Telegram bot stack
Transform: AWS::Serverless-2016-10-31
Parameters:
  TelegramToken:
    Type: String
    Description: Telegram bot token
    NoEcho: true
  TelegramChatId:
    Type: String
    Description: Telegram channel ID to send alerts to
Resources:
  StatusSnsTopic:
    Type: AWS::SNS::Topic
    Description: SNS topic for the CodePipeline events
    Properties:
      DisplayName: CodePipeline Statuses
      TopicName: CodePipelineStatuses
  StatusTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Description: Policy for status SNS topic
    Properties:
      Topics:
        - !Ref StatusSnsTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: StatusNotificationsPolicy
            Effect: Allow
            Principal:
              # CodeStar does the notifications. Thanks for consistency, AWS
              Service: codestar-notifications.amazonaws.com
              AWS: !Ref AWS::AccountId
            Action: sns:Publish
            Resource: !Ref StatusSnsTopic
          - Sid: __default_statement_ID
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - SNS:GetTopicAttributes
              - SNS:SetTopicAttributes
              - SNS:AddPermission
              - SNS:RemovePermission
              - SNS:DeleteTopic
              - SNS:Subscribe
              - SNS:ListSubscriptionsByTopic
              - SNS:Publish
              - SNS:Receive
            Resource: !Ref StatusSnsTopic
            Condition:
              StringEquals:
                AWS:SourceOwner: !Sub ${AWS::AccountId}
  StatusLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda function to handle CodePipeline events
      Runtime: go1.x
      MemorySize: 128
      Handler: status
      CodeUri: ../build/status.zip
      Timeout: 30
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref StatusSnsTopic
      Environment:
        Variables:
          TELEGRAM_TOKEN: !Ref TelegramToken
          CHAT_ID: !Ref TelegramChatId
